<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'doctrine.dbal.default_connection' shared service.

$a = new \Doctrine\DBAL\Logging\LoggerChain();
$a->addLogger(new \Symfony\Bridge\Doctrine\Logger\DbalLogger(($this->privates['logger'] ?? $this->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger()), NULL));
$a->addLogger(new \Doctrine\DBAL\Logging\DebugStack());

$b = new \Doctrine\DBAL\Configuration();
$b->setSQLLogger($a);

return $this->services['doctrine.dbal.default_connection'] = (new \Doctrine\Bundle\DoctrineBundle\ConnectionFactory(array()))->createConnection(array('driver' => 'pdo_mysql', 'charset' => 'UTF8', 'host' => '127.0.0.1', 'dbname' => 'doctrine_test_bundle', 'user' => 'root', 'password' => NULL, 'port' => NULL, 'driverOptions' => array(), 'serverVersion' => 5.5, 'defaultTableOptions' => array()), $b, new \Symfony\Bridge\Doctrine\ContainerAwareEventManager($this), array());
